### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by TSarkar2000** [RemiTheWarrior/epidemic-simulator#1]
No module named 'requests'.

This is the complete error message:

F:\epidemic-simulator-master>py fit_any_country.py China
Traceback (most recent call last):
  File "fit_any_country.py", line 2, in <module>
    from data import get_data
  File "F:\epidemic-simulator-master\data.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**NOTE:** I have matplotlib & scipy installed.

**Comment by RemDelaporteMathurin** [comment]
Is this still an issue ? :-)

**Comment by BilelJegham** [comment]
Fix in PR #2

We had requirements.txt to simplify Prerequisites

**Comment by TSarkar2000** [comment]
No.. I realized that I was missing python requests module. Installed it using pip.
Fault on my part. Sorry. :-)
