### ISSUE TITLE
Better fit for US?

### ISSUE THREAD

**Issue by adjavaherian** [RemiTheWarrior/epidemic-simulator#17]
Any idea how we can get a better fit for the US?

![Screen Shot 2020-03-29 at 12 35 55 PM](https://user-images.githubusercontent.com/3650448/77854807-688abd00-71ba-11ea-8fd6-f45771770e36.png)

**Comment by RemDelaporteMathurin** [comment]
Hi ! One way could be to tweak the parameters a bit (initial guess, or `x_n`)

**Comment by RemDelaporteMathurin** [comment]
Hi @adjavaherian,
By increasing parameter `x_n` I managed to get a far better fit. 
![image](https://user-images.githubusercontent.com/40028739/78031966-90b61f80-7364-11ea-97d6-0d6fdac97815.png)

**Comment by inetkenya** [comment]
Looks decent..let me see the extent of your adjustment, what figure did you alter x_n to? I can't seem to fit it no matter what value I put in there

**Comment by adjavaherian** [comment]
Yeah, I also tried updating x_n without nearly reasonable results.  I thought x_n was intended to be arbitrary?  What value did you use exactly, and what is thinking behind the value.  In any event, your model now seems to fit better with what the public health officials are reporting from their models here.  Thanks.

**Comment by inetkenya** [comment]
> Yeah, I also tried updating x_n without nearly reasonable results. I thought x_n was intended to be arbitrary? What value did you use exactly, and what is thinking behind the value. In any event, your model now seems to fit better with what the public health officials are reporting from their models here. Thanks.

Can you fit US and show me your chart. Have you adjusted anything apart from x_n? If so then please share it here

**Comment by RemDelaporteMathurin** [comment]
I used `x_n = 3e5` without changing anything else.
Even if the figures in the US are incredibly high, I think it's still the beginning of the epidemic there. So this fit has a lot of uncertainties... it has to be taken with great care !

**Comment by RemDelaporteMathurin** [comment]
@adjavaherian `x_n` is supposed to be the initial number of healthy people. Yet if it is set to the actual population of a country, I've never managed to fit anything. I'm not an epidiemologist myself so I reckon there must be something I still don't fully understand in the SIR modelling.

**Comment by Freakwill** [comment]
@RemiTheWarrior  Is it possible that the numbers in the y-axis are so high that make the gap between points and the line very narrow.

**Comment by RemDelaporteMathurin** [comment]
Hi @Freakwill, I'm not sure I get what you mean. Could you provide more details ?

**Comment by Freakwill** [comment]
> Hi @Freakwill, I'm not sure I get what you mean. Could you provide more details ?

Just ignore it, my English is weak. I just though the scale of y-axis might make our eyes to mis-estimate the fitting result. 
btw, the web dose not work well.
