### ISSUE TITLE
Portugal Fitness

### ISSUE THREAD

**Issue by cityxdev** [RemiTheWarrior/epidemic-simulator#19]
Hi Remi,

I'm curious about certain countries data being very different from the simulation.
I am using this data on a dashboard for country comparison, directly from your repository (most recent json file under data).

I give you an example, with 2 very "unfit" countries and a very fit one: Portugal (yellow), Netherlands (orange) and Germany (purple).
![Image 1](https://user-images.githubusercontent.com/55859758/79250159-304fd380-7e76-11ea-97fa-8a324df9f3dc.png)

Thanks

**Comment by RemDelaporteMathurin** [comment]
Hi @cityxdev 
The germany case isn't that bad on my side:
![image](https://user-images.githubusercontent.com/40028739/79255128-11f1d400-7e86-11ea-9981-1be5e9fd26c4.png)
Concerning Portugal I admit it's hard to fit the data. We'll see in the near future when more data points are available.

**Comment by cityxdev** [comment]
Germany is actually very good. It is in the example just as context.
I was talking about Portugal and The Netherlands. 

Should I tweak anything and run it on my side? Or is it better to just wait for more data points for those countries?
